Atest: fix NoneType of atest_unittest.py.
Running unit tests will seldom encounter flaky test failure:
  self.assertTrue(data_time)
  AssertionError: None is not true
tempfile.mkdkdtemp() generates hashed filename which contains "_" so the
previous parsing would be faulty when the string is YYYYMMDD_HHMM__<hash>

Bug: 147202893

Test: source build/envsetup.sh; lunch
  croot tools/tradefederation/core/atest
  ./run_atest_unittests.sh
  ./atest_run_unittests.py

Change-Id: I02d15d79765d94882b67f86b0c733a02ae357284